[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "preview"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = "contact"

  [[plugins.inputs.audits]]
    path = "ueber-odis"

  [[plugins.inputs.audits]]
    path = "module"

  [[plugins.inputs.audits]]
    path = "module/01-datenpotenziale-verstehen"

  [[plugins.inputs.audits]]
    path = "projekte"

  [[plugins.inputs.audits]]
    path = "projekte/2023-06-kiezcolors"

  [[plugins.inputs.audits]]
    path = "aktuelles"

  [[plugins.inputs.audits]]
    path = "aktuelles/2023-12-21-luftguete"

  [[plugins.inputs.audits]]
    path = "ressourcen"
  
  [[plugins.inputs.audits]]
    path = "ressourcen/01_open_data_in_verwaltung"